const COLLEGESDATA = [
  {
    name: "Harvard University",
    city: "Cambridge",
    state: "MA",
    country: "USA",
    no_of_students: 20000,
    courses: ["Computer Science", "Law", "Business", "Medicine", "Engineering"],
    website_url: "https://www.harvard.edu",
  },
  {
    name: "Stanford University",
    city: "Stanford",
    state: "CA",
    country: "USA",
    no_of_students: 17000,
    courses: ["Computer Science", "Engineering", "Business", "Law", "Medicine"],
    website_url: "https://www.stanford.edu",
  },
  {
    name: "Massachusetts Institute of Technology (MIT)",
    city: "Cambridge",
    state: "MA",
    country: "USA",
    no_of_students: 11500,
    courses: [
      "Computer Science",
      "Engineering",
      "Physics",
      "Mathematics",
      "Biology",
    ],
    website_url: "https://www.mit.edu",
  },
  {
    name: "University of California, Berkeley (UC Berkeley)",
    city: "Berkeley",
    state: "CA",
    country: "USA",
    no_of_students: 42000,
    courses: [
      "Computer Science",
      "Business",
      "Engineering",
      "Political Science",
      "Economics",
    ],
    website_url: "https://www.berkeley.edu",
  },
  {
    name: "Columbia University",
    city: "New York",
    state: "NY",
    country: "USA",
    no_of_students: 31000,
    courses: ["Law", "Business", "Engineering", "Medicine", "Journalism"],
    website_url: "https://www.columbia.edu",
  },
  {
    name: "University of Chicago",
    city: "Chicago",
    state: "IL",
    country: "USA",
    no_of_students: 17000,
    courses: [
      "Economics",
      "Political Science",
      "Mathematics",
      "Law",
      "Physics",
    ],
    website_url: "https://www.uchicago.edu",
  },
  {
    name: "Princeton University",
    city: "Princeton",
    state: "NJ",
    country: "USA",
    no_of_students: 8300,
    courses: [
      "Public Policy",
      "Mathematics",
      "Physics",
      "Engineering",
      "Computer Science",
    ],
    website_url: "https://www.princeton.edu",
  },
  {
    name: "Yale University",
    city: "New Haven",
    state: "CT",
    country: "USA",
    no_of_students: 14000,
    courses: ["Law", "Political Science", "Medicine", "History", "Economics"],
    website_url: "https://www.yale.edu",
  },
  {
    name: "California Institute of Technology (Caltech)",
    city: "Pasadena",
    state: "CA",
    country: "USA",
    no_of_students: 2200,
    courses: [
      "Engineering",
      "Physics",
      "Mathematics",
      "Computer Science",
      "Biology",
    ],
    website_url: "https://www.caltech.edu",
  },
  {
    name: "University of Michigan",
    city: "Ann Arbor",
    state: "MI",
    country: "USA",
    no_of_students: 46000,
    courses: ["Engineering", "Business", "Medicine", "Law", "Computer Science"],
    website_url: "https://www.umich.edu",
  },
];

export default COLLEGESDATA;
// const COLLEGESDATA = [
//   { name: "Harvard University", location: "Cambridge, MA", ranking: 1 },
//   { name: "Stanford University", location: "Stanford, CA", ranking: 2 },
//   {
//     name: "Massachusetts Institute of Technology (MIT)",
//     location: "Cambridge, MA",
//     ranking: 3,
//   },
//   {
//     name: "University of California, Berkeley (UC Berkeley)",
//     location: "Berkeley, CA",
//     ranking: 4,
//   },
//   { name: "Columbia University", location: "New York, NY", ranking: 5 },
//   { name: "University of Chicago", location: "Chicago, IL", ranking: 6 },
//   { name: "Princeton University", location: "Princeton, NJ", ranking: 7 },
//   { name: "Yale University", location: "New Haven, CT", ranking: 8 },
//   {
//     name: "California Institute of Technology (Caltech)",
//     location: "Pasadena, CA",
//     ranking: 9,
//   },
//   { name: "University of Michigan", location: "Ann Arbor, MI", ranking: 10 },
// ];
